steps:

  # Install node packages
  - name: 'gcr.io/cloud-builders/npm:latest'
    args: [ 'install' ]
    dir: 'frontend'
    id: install
    waitFor: [ '-' ]

  # Build
  - name: 'gcr.io/cloud-builders/npm:latest'
    args: [ 'run', 'build' ]
    dir: 'frontend'
    id: build
    waitFor: 
      - install

  # Test
  - name: 'gcr.io/cloud-builders/npm:latest'
    args: [ 'run', 'test']
    dir: 'frontend'
    id: test
    waitFor:
      - build
