# Note: Going to hold back on creating a trigger for CD for now.

steps: 

  # Install node packages
  - name: 'gcr.io/cloud-builders/npm:node-10.10.0'
    args: [ 'install' ]
    dir: 'frontend'
    id: install
    waitFor: [ '-' ]

  # Build webapp
  - name: 'gcr.io/cloud-builders/npm:node-14.4.0'
    args: [ 'run', 'buildprod' ]
    dir: 'frontend'
    id: build
    waitFor:
      - install

  # Deploy WAR
  - name: maven:3-jdk-8
    entrypoint: mvn
    args: ['package', 'appengine:deploy']
    dir: 'backend'
    id: deploy
    waitFor:
      - build