 
# GitHub Actions docs
# https://help.github.com/en/articles/about-github-actions
# https://help.github.com/en/articles/workflow-syntax-for-github-actions
name: frontend-ci

on: [pull_request, push]

jobs:
  build:

    # Machine environment:
    # https://help.github.com/en/articles/software-in-virtual-environments-for-github-actions#ubuntu-1804-lts
    # We specify the Node.js version manually below, and use versioned Chrome from Puppeteer.
    runs-on: ubuntu-18.04
    env:
      working-directory: ./frontend

    steps:
    - uses: actions/checkout@v2

    - name: Use Node.js 14.5.0
      uses: actions/setup-node@v1
      with:
        node-version: 14.5.0

    - name: Install dependencies
      run: npm install
      working-directory: ${{env.working-directory}}

    - name: Lint
      run: npm run lint
      working-directory: ${{env.working-directory}}

    - name: Build
      run: npm run ci-build
      working-directory: ${{env.working-directory}}

    - name: Test
      run: npm run ci-test
      working-directory: ${{env.working-directory}}